[package]
name = "milena-protos"
version = "0.1.0"
edition = "2021"


[dependencies]
prost = "0.11.5"
tonic = "0.8.3"
tokio = { version = "1", features = ["full"] }

[build-dependencies]
tonic-build = "0.8.4"
