[package]
name = "milena-protos"
version = "0.1.0"
edition = "2021"


[dependencies]
prost = "0.12.1"
tonic = "0.10.2"
tokio = { version = "1", features = ["full"] }

[build-dependencies]
tonic-build = "0.10.2"
